import fs from 'fs';
import path from 'path';

// Generate a valid base64 PNG icon (Blue background with white PDF text)
const base64Png = 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAedEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHmUACorAAACs0lEQVR42u3TQQ0AAAgEwS+/6FlDC1yE/fM2M3C2fQcQIBAGCEEACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAI BghBAAgGCEDACAYIQQAIBghBAAC/G3o4A3I9bN5/AAAAAElFTkSuQmCC';

const publicDir = path.join(process.cwd(), 'public');
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

fs.writeFileSync(path.join(publicDir, 'pwa-192.png'), Buffer.from(base64Png, 'base64'));
fs.writeFileSync(path.join(publicDir, 'pwa-512.png'), Buffer.from(base64Png, 'base64'));

console.log('PWA icons created in /public');
